name: "Test Action"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "It should run Ansible playbook"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "9.3.0"

      - name: "Apply playbook"
        uses: ./
        with:
            inventory: "inventory.yml"
            playbook: "playbook.yml"
            private-key: "private_key"
            become-password: "password"
            become-user: "root"
            become-method: "sudo"
            tags: "tag1,tag2"
            skip-tags: "tag3,tag4"
            vault-password: "vault_password"
            check-only: "true"
            user: "user"
            debug: "true"
            extra_variables: "key1=value1, key2=value2"
